version: '3.6'

services:
  api:
    container_name: umba-transfer-api
    build: .
    env_file: db/database.conf
    depends_on:
      - postgres
    environment:
      STAGE: test
      SQLALCHEMY_DATABASE_URI: "postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"
    networks:
      - KAKA
    ports:
      - 5000:5000
    volumes:
      - ./transfer_flask:/usr/src/app/transfer_flask
      - ./migrations:/usr/src/app/migrations
    restart: always

  postgres:
    hostname: postgres
    env_file: db/database.conf
    container_name: postgres_db
    image: postgres:latest
    networks:
      - KAKA
    ports:
      - "5405:${POSTGRES_PORT}"
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d/:ro

networks:
  KAKA:
    driver: bridge

